### ISSUE TITLE
Custom Exception 도입 추천

### ISSUE THREAD

**Issue by BYEONGRYEOL** [alaneelee/assignment1#1]
```java
public class CustomExceptionHandler {

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgumentException(IllegalArgumentException ex) {

        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.UNAUTHORIZED.name(), HttpStatus.UNAUTHORIZED.value(), ex.getMessage());

        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(errorResponse);
    }
}
``` 

CustomExceptionHandler 클래스에서 IllegalArgumentException이 발생할 때마다 handleIllegalArgumentException 함수를 거치게 됩니다.
현재는 IllegalArgumentException이 발생하는 원인이 게시글 수정,삭제의 비밀번호 불일치인 경우밖에 없지만, 서비스가 확장됨에 따라 서로 다른 많은 예외를 handle하게 될 수 있으니 java의 Custom Exception class를 생성하여 handler와 1대1 매치하는건 어떨까요?

**Comment by alaneelee** [comment]
확실히 확장성에서 불리한 측면이 있을 것 같아 바로 반영하였습니다.
감사합니다!
[Custom Exception 도입](https://github.com/alaneelee/assignment1/commit/2101ed9c47919e833468435a2acde84aa21c5d79)
